### ISSUE TITLE
Add search functionality to docs

### ISSUE THREAD

**Issue by michielvandergeest** [lightning-js/lightningjs.io#58]
The docs on the website are not searchable like the docsify docs hosted on Github (i.e. https://lightning-js.github.io/blits/#/getting_started/getting_started) are.

We should add a similar type of search functionality for the docs hosted on the website as well.

**Comment by krisantuswanandi** [comment]
any reason why the search is disabled?

https://github.com/lightning-js/lightningjs.io/blob/aca60034bf1d4f62433c9f3664bdc9d9d40ed303/site/.vitepress/config.mjs#L61-L63
